language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy

script:
  - cargo build --verbose
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --verbose

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
